Add helm lint

diff --git a/.github/workflows/build-containers.yml b/.github/workflows/build-containers.yml
--- a/.github/workflows/build-containers.yml
+++ b/.github/workflows/build-containers.yml
@@ -223,6 +223,13 @@ jobs:
           repository: 'flowfuse/helm'
           fetch-depth: 0
           path: 'helm'
+      - name: Helm lint
+        run: |
+          helm lint --quiet helm/helm/flowforge
+          if [ $? -ne 0 ]; then
+            echo "helm lint failed."
+            exit 1
+          fi
       - name: Package
         run: |
           helm package -d . helm/helm/flowforge
